# config/packages/nucleos_user.yaml
nucleos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email: "%mailer_user%"
    group:
        group_class: App\Entity\Group